### ISSUE TITLE
Doesn't support numerical 2?

### ISSUE THREAD

**Issue by jessicatjahja** [doms/spongemock#7]
/mock 20 outputs 0
/mock 20_20 outputs 0?2
/mock 2 doesn't produce an output

Unclear of any other patterns

**Comment by doms** [comment]
@jessicatjahja 👋 

woah, that's really weird! I will investigate and get back to you _soon_ ™️

**Comment by doms** [comment]
Hey @jessicatjahja! Try it out now! 😄
